-- ============================================
-- CR-Check Hybrid RAG DB Schema
-- Migration: 20260328000000_create_cr_check_schema
--
-- 기반 문서: DB_AND_RAG_MASTER_PLAN_v4.0.md 섹션 6.1
--            DB_BUILD_EXECUTION_GUIDE.md 섹션 2-2
-- 앙상블 검증 반영 (2026-03-25):
--   - ivfflat 인덱스 제거 (5/5 합의)
--   - is_citable 컬럼 추가 (5/5 합의)
--   - 재귀 CTE 롤업 (get_ethics_for_patterns)
--   - KJA → JCE 접두어 수정
-- ============================================

-- ============================================
-- 0. Extension
-- ============================================
CREATE EXTENSION IF NOT EXISTS vector;

-- ============================================
-- 1. 문제적 보도관행 패턴 (Phase 0)
-- ============================================
CREATE TABLE public.patterns (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code TEXT NOT NULL UNIQUE,
  name TEXT NOT NULL,
  description TEXT NOT NULL,
  category TEXT,
  subcategory TEXT,
  is_meta_pattern BOOLEAN DEFAULT FALSE,
  hierarchy_level INT,          -- 1=대분류, 2=중분류, 3=소분류
  parent_pattern_id BIGINT REFERENCES public.patterns(id),
  locale TEXT NOT NULL DEFAULT 'ko-KR',
  description_embedding vector(1536),
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

CREATE INDEX idx_patterns_code ON public.patterns(code);
CREATE INDEX idx_patterns_locale ON public.patterns(locale);
-- 벡터 인덱스 불필요: ~102개 패턴 규모에서 sequential scan이
-- 100% recall + 1ms 미만 응답으로 ivfflat/HNSW보다 우수.
-- 1만 건 이상 확장 시 HNSW 도입 검토. (앙상블 검증 2026-03-25, 5/5 합의)

-- ============================================
-- 2. 언론윤리규범 조항 (Phase 0, 버전 관리 포함)
-- ============================================
CREATE TABLE public.ethics_codes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code TEXT NOT NULL,
  title TEXT NOT NULL,
  full_text TEXT NOT NULL,
  source TEXT NOT NULL,
  article_number TEXT,
  tier INT NOT NULL CHECK (tier BETWEEN 1 AND 4),
  tier_rationale TEXT,
  parent_code_id BIGINT REFERENCES public.ethics_codes(id),
  domain TEXT DEFAULT 'general',
  locale TEXT NOT NULL DEFAULT 'ko-KR',
  -- 버전 관리
  version INT NOT NULL DEFAULT 1,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  effective_from DATE NOT NULL DEFAULT CURRENT_DATE,
  effective_until DATE,
  superseded_by BIGINT REFERENCES public.ethics_codes(id),
  change_reason TEXT,
  -- 인용 적합성 필터 (앙상블 검증 5/5 합의)
  is_citable BOOLEAN NOT NULL DEFAULT TRUE,
  text_embedding vector(1536),
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now(),
  CONSTRAINT unique_ethics_code_version UNIQUE (code, version)
);

CREATE INDEX idx_ethics_code ON public.ethics_codes(code);
CREATE INDEX idx_ethics_locale ON public.ethics_codes(locale);
CREATE INDEX idx_ethics_active ON public.ethics_codes(is_active);
-- 벡터 인덱스 불필요: ~160개 규범 규모에서 sequential scan 충분.

-- ============================================
-- 3. 규범 위계 관계 — 다대다 대비 Junction Table (Phase 0)
-- ============================================
CREATE TABLE public.ethics_code_hierarchy (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  parent_code_id BIGINT REFERENCES public.ethics_codes(id) NOT NULL,
  child_code_id BIGINT REFERENCES public.ethics_codes(id) NOT NULL,
  relation_note TEXT,
  CONSTRAINT unique_hierarchy UNIQUE (parent_code_id, child_code_id)
);

-- ============================================
-- 4. 패턴 ↔ 윤리규범 관계 (Phase 0)
-- ============================================
CREATE TABLE public.pattern_ethics_relations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  pattern_id BIGINT REFERENCES public.patterns(id) ON DELETE CASCADE NOT NULL,
  ethics_code_id BIGINT REFERENCES public.ethics_codes(id) ON DELETE CASCADE NOT NULL,
  relation_type TEXT NOT NULL CHECK (relation_type IN (
    'violates', 'related_to', 'exception_of'
  )),
  strength TEXT DEFAULT 'moderate' CHECK (strength IN ('strong', 'moderate', 'weak')),
  reasoning TEXT,
  examples TEXT,
  created_at TIMESTAMPTZ DEFAULT now(),
  CONSTRAINT unique_pattern_ethics UNIQUE (pattern_id, ethics_code_id, relation_type)
);

CREATE INDEX idx_rel_pattern ON public.pattern_ethics_relations(pattern_id);
CREATE INDEX idx_rel_ethics ON public.pattern_ethics_relations(ethics_code_id);

-- ============================================
-- 5. 패턴 간 관계 (Phase 0)
-- ============================================
CREATE TABLE public.pattern_relations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  source_pattern_id BIGINT REFERENCES public.patterns(id) NOT NULL,
  target_pattern_id BIGINT REFERENCES public.patterns(id) NOT NULL,
  relation_type TEXT NOT NULL CHECK (relation_type IN (
    'co_occurs', 'escalates_to', 'variant_of', 'inferred_by'
  )),
  description TEXT,
  source TEXT DEFAULT 'manual' CHECK (source IN (
    'manual', 'embedding_similarity', 'llm_extracted', 'co_occurrence_mined'
  )),
  confidence FLOAT DEFAULT 1.0,
  verified BOOLEAN DEFAULT FALSE,
  CONSTRAINT unique_pattern_rel UNIQUE (source_pattern_id, target_pattern_id, relation_type)
);

-- ============================================
-- 6. Articles — 기사 메타데이터 (Phase 1, Auth 제거)
-- ============================================
CREATE TABLE public.articles (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  url TEXT NOT NULL,
  title TEXT NOT NULL,
  publisher TEXT,
  journalist TEXT,
  publish_date TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT now() NOT NULL,
  CONSTRAINT articles_url_key UNIQUE (url)
);

CREATE INDEX idx_articles_url ON public.articles(url);
CREATE INDEX idx_articles_publisher ON public.articles(publisher);
CREATE INDEX idx_articles_created_at ON public.articles(created_at DESC);

COMMENT ON TABLE public.articles IS '기사 원본 메타데이터 (중복 분석 방지용)';

-- ============================================
-- 7. Analysis Results — AI 분석 결과 (Phase 1, Auth 제거)
-- ============================================
CREATE TABLE public.analysis_results (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  article_id BIGINT REFERENCES public.articles(id) ON DELETE CASCADE NOT NULL,
  comprehensive_report TEXT,
  journalist_report TEXT,
  student_report TEXT,
  phase1_model TEXT DEFAULT 'claude-haiku-4-5-20251001',
  phase2_model TEXT DEFAULT 'claude-sonnet-4-6',
  duration_seconds FLOAT,
  detected_categories JSONB,
  created_at TIMESTAMPTZ DEFAULT now() NOT NULL
);

CREATE INDEX idx_analysis_article ON public.analysis_results(article_id);
CREATE INDEX idx_analysis_created_at ON public.analysis_results(created_at DESC);

COMMENT ON TABLE public.analysis_results IS 'AI 분석 결과 저장 (익명, 공개 URL 공유)';
COMMENT ON COLUMN public.analysis_results.detected_categories IS 'Phase 1에서 탐지된 문제 카테고리 ID 목록';

-- ============================================
-- 8. Feedbacks — 익명 사용자 피드백 (Phase 3 활성화)
-- ============================================
CREATE TABLE public.feedbacks (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  analysis_id BIGINT REFERENCES public.analysis_results(id) ON DELETE CASCADE NOT NULL,
  rating INT CHECK (rating BETWEEN 1 AND 5),
  comment TEXT,
  created_at TIMESTAMPTZ DEFAULT now() NOT NULL
);

CREATE INDEX idx_feedbacks_analysis ON public.feedbacks(analysis_id);

COMMENT ON TABLE public.feedbacks IS '익명 사용자 피드백 (user_id 없이 analysis_id + rating + comment만 저장)';

-- ============================================
-- 9. 분석 리포트 규범 스냅샷 — 시점 보존 (Phase 0)
-- ============================================
CREATE TABLE public.analysis_ethics_snapshot (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  analysis_id BIGINT REFERENCES public.analysis_results(id) ON DELETE CASCADE NOT NULL,
  ethics_code_id BIGINT REFERENCES public.ethics_codes(id) NOT NULL,
  snapshot_full_text TEXT NOT NULL,
  snapshot_version INT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT now()
);

COMMENT ON TABLE public.analysis_ethics_snapshot IS
  '분석 리포트가 참조한 규범 조항의 시점 스냅샷.
   규범이 개정되어도 과거 리포트의 인용 근거가 보존됨.
   저장 범위: Sonnet이 실제로 <cite ref/>로 인용한 규범만 스냅샷.';

-- ============================================
-- 10. 뷰: 활성 규범만 검색
-- ============================================
CREATE VIEW public.active_ethics_codes AS
  SELECT * FROM public.ethics_codes WHERE is_active = TRUE;

-- ============================================
-- 11. 뷰: 규범 변경 이력 추적
-- ============================================
CREATE VIEW public.ethics_codes_history AS
  SELECT ec.code, ec.version, ec.title,
         ec.effective_from, ec.effective_until,
         ec.is_active, ec.change_reason,
         successor.code AS successor_code,
         successor.version AS successor_version
  FROM public.ethics_codes ec
  LEFT JOIN public.ethics_codes successor ON ec.superseded_by = successor.id
  ORDER BY ec.code, ec.version;

-- ============================================
-- 12. RPC 함수: 패턴 후보 검색 (Haiku 단계용)
-- ============================================
CREATE OR REPLACE FUNCTION search_pattern_candidates(
  query_embedding vector(1536),
  match_threshold FLOAT DEFAULT 0.5,
  match_count INT DEFAULT 10
)
RETURNS TABLE (
  pattern_id BIGINT,
  pattern_code TEXT,
  pattern_name TEXT,
  pattern_description TEXT,
  similarity FLOAT
) AS $$
BEGIN
  RETURN QUERY
  SELECT p.id, p.code, p.name, p.description,
         1 - (p.description_embedding <=> query_embedding) AS similarity
  FROM public.patterns p
  WHERE p.is_meta_pattern = FALSE
    AND 1 - (p.description_embedding <=> query_embedding) > match_threshold
  ORDER BY similarity DESC
  LIMIT match_count;
END;
$$ LANGUAGE plpgsql STABLE;

-- ============================================
-- 13. RPC 함수: 확정 패턴에 대한 규범 정밀 조회 + 롤업 parent chain
--     (Sonnet 단계용, 앙상블 검증 반영: 재귀 CTE)
--     UNION을 통해 직접 관계와 롤업 관계의 중복을 자연스럽게 제거함
-- ============================================
CREATE OR REPLACE FUNCTION get_ethics_for_patterns(
  confirmed_pattern_ids BIGINT[]
)
RETURNS TABLE (
  pattern_id BIGINT,
  pattern_code TEXT,
  ethics_code_id BIGINT,
  ethics_code TEXT,
  ethics_title TEXT,
  ethics_full_text TEXT,
  ethics_tier INT,
  relation_type TEXT,
  strength TEXT,
  reasoning TEXT
) AS $$
BEGIN
  RETURN QUERY
  WITH RECURSIVE direct_codes AS (
    -- 1단계: pattern_ethics_relations에서 직접 연결된 규범
    SELECT per.pattern_id, p.code AS p_code,
           ec.id AS ec_id, ec.code AS ec_code, ec.title, ec.full_text, ec.tier,
           per.relation_type, per.strength, per.reasoning
    FROM public.pattern_ethics_relations per
    JOIN public.patterns p ON per.pattern_id = p.id
    JOIN public.active_ethics_codes ec ON per.ethics_code_id = ec.id
    WHERE per.pattern_id = ANY(confirmed_pattern_ids)
      AND ec.is_citable = TRUE
  ),
  parent_chain AS (
    -- 2단계: 직접 규범의 parent chain을 재귀적으로 수집 (구체→포괄 롤업)
    -- [C-01 fix] pattern_id를 base case에서 상속하여 CROSS JOIN 제거
    -- [W-01 fix] depth 카운터로 무한 루프 방지 (최대 5)
    SELECT dc.pattern_id, dc.p_code,
           ec.id, ec.code, ec.title, ec.full_text, ec.tier, ec.parent_code_id,
           1 AS depth
    FROM public.ethics_codes ec
    JOIN direct_codes dc ON ec.id = dc.ec_id
    WHERE ec.is_active = TRUE
    UNION
    SELECT child.pattern_id, child.p_code,
           parent.id, parent.code, parent.title, parent.full_text, parent.tier, parent.parent_code_id,
           child.depth + 1
    FROM public.ethics_codes parent
    JOIN parent_chain child ON parent.id = child.parent_code_id
    WHERE parent.is_active = TRUE
      AND parent.is_citable = TRUE
      AND child.depth < 5
  )
  -- 직접 관계 규범 반환
  SELECT dc.pattern_id, dc.p_code,
         dc.ec_id, dc.ec_code, dc.title, dc.full_text, dc.tier,
         dc.relation_type, dc.strength, dc.reasoning
  FROM direct_codes dc
  UNION
  -- 롤업 상위 규범 반환 (직접 관계에 없는 parent만, 패턴별 범위 대조)
  SELECT DISTINCT pc.pattern_id, pc.p_code,
         pc.id, pc.code, pc.title, pc.full_text, pc.tier,
         'related_to'::TEXT, 'moderate'::TEXT, 'parent chain rollup'::TEXT
  FROM parent_chain pc
  WHERE NOT EXISTS (
    SELECT 1 FROM direct_codes dc
    WHERE dc.ec_id = pc.id
      AND dc.pattern_id = pc.pattern_id
  )
  ORDER BY tier;
END;
$$ LANGUAGE plpgsql STABLE;

-- ============================================
-- 14. Phase 2 통계 함수: 실시간 트렌드
-- ============================================
CREATE OR REPLACE FUNCTION get_trending_articles(hours_ago INT DEFAULT 24)
RETURNS TABLE (
  article_id BIGINT,
  title TEXT,
  url TEXT,
  publisher TEXT,
  analysis_count BIGINT,
  latest_analysis TIMESTAMPTZ
) AS $$
BEGIN
  RETURN QUERY
  SELECT a.id, a.title, a.url, a.publisher,
         COUNT(ar.id) AS analysis_count,
         MAX(ar.created_at) AS latest_analysis
  FROM public.articles a
  JOIN public.analysis_results ar ON a.id = ar.article_id
  WHERE ar.created_at >= NOW() - INTERVAL '1 hour' * hours_ago
  GROUP BY a.id, a.title, a.url, a.publisher
  ORDER BY analysis_count DESC, latest_analysis DESC
  LIMIT 10;
END;
$$ LANGUAGE plpgsql STABLE;

-- ============================================
-- 15. Phase 2 통계 함수: 언론사별 통계
-- ============================================
CREATE OR REPLACE FUNCTION get_publisher_stats()
RETURNS TABLE (
  publisher TEXT,
  total_analyses BIGINT,
  avg_duration FLOAT
) AS $$
BEGIN
  RETURN QUERY
  SELECT a.publisher, COUNT(ar.id), AVG(ar.duration_seconds)
  FROM public.articles a
  JOIN public.analysis_results ar ON a.id = ar.article_id
  WHERE a.publisher IS NOT NULL
  GROUP BY a.publisher
  ORDER BY total_analyses DESC
  LIMIT 20;
END;
$$ LANGUAGE plpgsql STABLE;

-- ============================================
-- 16. Phase 2 통계 함수: 전체 통계 요약 (Auth 제거)
-- ============================================
CREATE OR REPLACE FUNCTION get_overall_stats()
RETURNS TABLE (
  total_articles BIGINT,
  total_analyses BIGINT,
  avg_duration FLOAT
) AS $$
BEGIN
  RETURN QUERY
  SELECT COUNT(DISTINCT a.id),
         COUNT(ar.id),
         AVG(ar.duration_seconds)
  FROM public.articles a
  LEFT JOIN public.analysis_results ar ON a.id = ar.article_id;
END;
$$ LANGUAGE plpgsql STABLE;

-- ============================================
-- 17. 공용 트리거 함수: updated_at 자동 갱신
-- ============================================
CREATE OR REPLACE FUNCTION handle_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER set_patterns_updated_at
  BEFORE UPDATE ON public.patterns
  FOR EACH ROW
  EXECUTE FUNCTION handle_updated_at();

CREATE TRIGGER set_ethics_codes_updated_at
  BEFORE UPDATE ON public.ethics_codes
  FOR EACH ROW
  EXECUTE FUNCTION handle_updated_at();
